name: mai_app
description: "MAI - Math AI Assistant"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  
  # HTTP запросы
  http: ^1.2.0
  
  # State management
  provider: ^6.1.1
  
  # Для работы с JSON
  json_annotation: ^4.8.1
  
  # Камера
  camera: ^0.11.0
  image_picker: ^1.0.7
  
  # UI компоненты
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  
  # Локальное хранилище
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true